version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234  
      MYSQL_DATABASE: prueba
    ports:
      - "3307:3306"  
    volumes:
      - mysql-data:/var/lib/mysql           # Mount a named volume for MySQL 

  fastapi-app:
    build: 
      context: .
    container_name: fastapi_app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql

volumes:
  mysql-data:   # Named volume for MySQL data