"""init

Revision ID: 58a5206d5805
Revises: 
Create Date: 2024-07-12 11:28:22.763954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a5206d5805'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parameters_id'), 'parameters', ['id'], unique=False)
    op.create_table('type_parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_parameters_id'), 'type_parameters', ['id'], unique=False)
    op.create_table('types_per_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Value', sa.Text(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=True),
    sa.Column('type_parameter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameters.id'], ),
    sa.ForeignKeyConstraint(['type_parameter_id'], ['type_parameters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_types_per_model_id'), 'types_per_model', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_types_per_model_id'), table_name='types_per_model')
    op.drop_table('types_per_model')
    op.drop_index(op.f('ix_type_parameters_id'), table_name='type_parameters')
    op.drop_table('type_parameters')
    op.drop_index(op.f('ix_parameters_id'), table_name='parameters')
    op.drop_table('parameters')
    # ### end Alembic commands ###
